version: '3.4'

services:
 sqlserver:
  image: mcr.microsoft.com/mssql/server:2019-latest
  environment:
    SA_PASSWORD: "YourStrong!Passw0rd"
    ACCEPT_EULA: "Y"
  ports:
    - "1433:1433"
  volumes:
    - ./init.sql:/init.sql
  command: >
    /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 20 && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -i /init.sql &&
      tail -f /dev/null
    "
  healthcheck:
    test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
    interval: 10s
    retries: 10

 employeeapp:
  build: .
  depends_on:
    sqlserver:
      condition: service_healthy
  environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=employee;User Id=sa;Password=YourStrong!Passw0rd;
  ports:
    - "10000:10000"

